def exception_error(e):
    print("\nSome type of other exception is there")
    print(f"Error is:- {e}")

    # import traceback
    # print(traceback.format_exc())
    print()
